
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SOPT_Firstweek_HW_2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SOPT_Firstweek_HW_2
pod 'Alamofire', '~> 4.8.2'
pod 'Kingfisher', '~> 5.0'
pod 'BEMCheckBox'
end
